export const UI_TEXT = {
  appTitle: 'Haushaltsmitglieder',
  addPerson: 'Person hinzufügen',
  editPerson: 'Person bearbeiten',
  deletePerson: 'Löschen',
  edit: 'Bearbeiten',
  save: 'Speichern',
  cancel: 'Abbrechen',
  name: 'Name',
  category: 'Kategorie',
  size: 'Größe',
  avatar: 'Avatar',
  confirmDelete: 'Möchten Sie {name} wirklich löschen?',
  noPersons: 'Noch keine Personen vorhanden',
  addFirstPerson: 'Fügen Sie die erste Person hinzu',
  nameRequired: 'Name ist erforderlich',
  personAdded: 'Person erfolgreich hinzugefügt',
  personUpdated: 'Person erfolgreich aktualisiert',
  personDeleted: 'Person erfolgreich gelöscht',
  categories: {
    baby: 'Baby',
    kleinkind: 'Kleinkind',
    kind: 'Kind',
    erwachsener: 'Erwachsener'
  },
  clothing: {
    title: 'Kleidung',
    addClothing: 'Kleidung hinzufügen',
    editClothing: 'Kleidung bearbeiten',
    viewClothing: 'Kleidung anzeigen',
    allClothing: 'Alle Kleidung',
    backToDashboard: 'Zurück zur Übersicht',
    category: 'Kategorie',
    color: 'Farbe',
    brand: 'Marke',
    size: 'Größe',
    status: 'Status',
    notes: 'Notizen',
    owner: 'Besitzer',
    deleteClothing: 'Löschen',
    confirmDeleteClothing: 'Möchten Sie dieses Kleidungsstück wirklich löschen?',
    customCategory: 'Kategorie eingeben...',
    filterByPerson: 'Nach Person filtern',
    filterByCategory: 'Nach Kategorie filtern',
    allPersons: 'Alle Personen',
    allCategories: 'Alle Kategorien',
    statuses: {
      vorhanden: 'Passt noch',
      zu_klein: 'Zu klein',
      aussortiert: 'Aussortiert'
    },
    filters: {
      all: 'Alle',
      vorhanden: 'Passt noch',
      zu_klein: 'Zu klein',
      aussortiert: 'Aussortiert'
    },
    noClothing: 'Noch keine Kleidung erfasst',
    addFirstItem: 'Fügen Sie das erste Kleidungsstück hinzu',
    categoryRequired: 'Kategorie ist erforderlich',
    items: 'Teile',
    itemsToSmall: 'zu klein',
    itemsSorted: 'aussortiert',
    clothingAdded: 'Kleidungsstück erfolgreich hinzugefügt',
    clothingUpdated: 'Kleidungsstück erfolgreich aktualisiert',
    clothingDeleted: 'Kleidungsstück erfolgreich gelöscht',
    statusUpdated: 'Status erfolgreich aktualisiert'
  }
}
